[package]
name = "qubo_optimizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = "0.15.6"
ndarray-stats = "0.5.1"
ndarray-rand = "0.14.0"
rand = "0.8.5"
rand_pcg = "0.3.1"
serde_json = "1.0"
